// <auto-generated />
using BookStoreApp.Data.Concrete.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreApp.Data.Migrations
{
    [DbContext(typeof(BookStoreAppContext))]
    partial class BookStoreAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.15");

            modelBuilder.Entity("BookStoreApp.Entity.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "John Steinback"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Dostoyevski"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Tolstoy"
                        });
                });

            modelBuilder.Entity("BookStoreApp.Entity.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenreId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublisherId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            GenreId = 1,
                            Isbn = "bvncm",
                            PublisherId = 1,
                            Title = "Fareler ve İnsanlar",
                            TotalPages = 250
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            GenreId = 3,
                            Isbn = "xcvbtr",
                            PublisherId = 2,
                            Title = "Kumarbaz",
                            TotalPages = 450
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            GenreId = 2,
                            Isbn = "qwert",
                            PublisherId = 3,
                            Title = "İnsan Ne İle Yaşar",
                            TotalPages = 320
                        });
                });

            modelBuilder.Entity("BookStoreApp.Entity.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Psikoloji"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gezi"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Şiir"
                        });
                });

            modelBuilder.Entity("BookStoreApp.Entity.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublisherName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publishers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PublisherName = "Can Yayınları"
                        },
                        new
                        {
                            Id = 2,
                            PublisherName = "Martı Yayınları"
                        },
                        new
                        {
                            Id = 3,
                            PublisherName = "YKY Yayınları"
                        });
                });

            modelBuilder.Entity("BookStoreApp.Entity.Book", b =>
                {
                    b.HasOne("BookStoreApp.Entity.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreApp.Entity.Genre", "Genre")
                        .WithMany("Books")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BookStoreApp.Entity.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("BookStoreApp.Entity.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStoreApp.Entity.Genre", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("BookStoreApp.Entity.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
